### ISSUE TITLE
Checklist before Deploy

### ISSUE THREAD

**Issue by KRRISH96** [KRRISH96/saikrishna.dev#1]
- [x]  Fix Console Warning
- [x] Accessibility Check
- [x] Dynamic Copyright year in Footer
- [x] Organize CSS
- [x] Clean up dead code
- [x] Google Analytics
- [x] SEO check - metadata -descriptions etc.,
- [x] Fix Theme switching button position on medium and lower screens
- [x] External links plugin
- [x] Good dimensions for images
